all:
	go build main.go algorithms.go manual_testing.go auto_testing.go structs.go menu.go help_testing.go
	
graph:
	go build main.go algorithms.go manual_testing.go auto_testing.go structs.go menu.go graph.go help_testing.go
